import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

function read(name) {
  return readFileSync(resolve(__dirname, '../../public', name), 'utf-8');
}

function wrap(raw) {
  // Escape backtick and ${} for template literal
  return raw.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const indexHtml = wrap(read('index.html'));
const adminHtml = wrap(read('admin.html'));

const out = `// Auto-generated by embed-html.mjs - do not edit manually
export const INDEX_HTML: string = \`${indexHtml}\`;
export const ADMIN_HTML: string = \`${adminHtml}\`;
`;

writeFileSync(resolve(__dirname, '../../src/cloudflare/static_pages.ts'), out, 'utf-8');
console.log('static_pages.ts generated');
