// Auto-generated by embed-html.mjs - do not edit manually
export const INDEX_HTML: string = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<meta name="color-scheme" content="dark light">
<title>ClipRelay · 剪贴板接力</title>
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  color-scheme: light;
  --bg: #e9eaed;
  --surface: #ffffff;
  --surface-hover: #f8f9fb;
  --border: #e4e7ed;
  --text: #1e1f24;
  --text-secondary: #868b96;
  --text-muted: #a6aab2;
  --accent: #4f6ef6;
  --accent-light: #eef1fe;
  --accent-hover: #3d5de0;
  --accent-gradient: linear-gradient(135deg, #4f6ef6 0%, #7b5cf0 100%);
  --success: #10b981;
  --danger: #ef4444;
  --warning: #f59e0b;
  --radius-sm: 6px;
  --radius: 12px;
  --radius-lg: 18px;
  --shadow-sm: 0 1px 2px rgba(0,0,0,.04);
  --shadow: 0 2px 8px rgba(0,0,0,.06), 0 1px 2px rgba(0,0,0,.04);
  --shadow-lg: 0 8px 24px rgba(0,0,0,.08), 0 2px 4px rgba(0,0,0,.04);
  --code-bg: #f1f5f9;
  --highlight-bg: #eef1fe;
  --bubble-self: #95ec69;
  --bubble-self-text: #1a1a1a;
  --bubble-self-hover: #85d85a;
  --bubble-other: #c8d8f0;
  --transition: .2s cubic-bezier(.4,0,.2,1);
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #0d0f14;
  --surface: #161820;
  --surface-hover: #1c1e28;
  --border: #282b35;
  --text: #e3e5ec;
  --text-secondary: #8d919e;
  --text-muted: #5e6270;
  --accent: #6b8af7;
  --accent-light: #1a2040;
  --accent-hover: #8ba4f9;
  --accent-gradient: linear-gradient(135deg, #6b8af7 0%, #9080f0 100%);
  --success: #34d399;
  --danger: #f87171;
  --warning: #fbbf24;
  --shadow-sm: 0 1px 2px rgba(0,0,0,.2);
  --shadow: 0 2px 8px rgba(0,0,0,.3), 0 1px 2px rgba(0,0,0,.2);
  --shadow-lg: 0 8px 24px rgba(0,0,0,.4);
  --code-bg: #1e2030;
  --highlight-bg: #1a2040;
  --bubble-self: #1e4620;
  --bubble-self-text: #c8e6c9;
  --bubble-self-hover: #255428;
  --bubble-other: #1e2d45;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans SC", sans-serif;
  background: var(--bg);
  color: var(--text);
  height: 100dvh;
  height: 100vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  -webkit-font-smoothing: antialiased;
  position: fixed;
  inset: 0;
}

/* scrollbar */
::-webkit-scrollbar { width: 5px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--text-muted); border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: var(--text-secondary); }

/* --- 顶部栏 --- */
.header {
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 8px 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-shrink: 0;
  backdrop-filter: blur(12px);
}
.header-left { display: flex; align-items: center; gap: 10px; }
.logo {
  font-weight: 800;
  font-size: 16px;
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  letter-spacing: -.5px;
}
.room-token {
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 11px;
  color: var(--text-muted);
  background: var(--bg);
  padding: 3px 10px;
  border-radius: 20px;
  max-width: 140px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  border: 1px solid var(--border);
}
.header-right { display: flex; align-items: center; gap: 10px; }
.status-badge {
  font-size: 11px;
  padding: 3px 10px;
  border-radius: 20px;
  font-weight: 600;
  letter-spacing: .2px;
}
.status-badge.active { background: #ecfdf5; color: #059669; }
.status-badge.expiring { background: #fffbeb; color: #d97706; }
.status-badge.expired { background: #fef2f2; color: #dc2626; }
[data-theme="dark"] .status-badge.active { background: #064e3b; color: #34d399; }
[data-theme="dark"] .status-badge.expiring { background: #451a03; color: #fbbf24; }
[data-theme="dark"] .status-badge.expired { background: #450a0a; color: #f87171; }
.online-count {
  font-size: 11px;
  color: var(--text-muted);
  display: flex;
  align-items: center;
  gap: 5px;
}
.online-dot {
  width: 6px; height: 6px;
  border-radius: 50%;
  background: var(--success);
  display: inline-block;
  animation: pulse 2s infinite;
}
@keyframes pulse { 0%,100% { opacity:1 } 50% { opacity:.4 } }

/* --- 主内容区 --- */
.main {
  flex: 1;
  min-height: 0;
  display: flex;
  overflow: hidden;
}
.panel-messages {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 0;
  min-height: 0;
  background: var(--bg);
}

/* --- 消息列表 --- */
.msg-list {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
  overscroll-behavior: contain;
  padding: 12px 14px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.msg-list:empty::after {
  content: "等待消息…";
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: var(--text-muted);
  font-size: 14px;
  align-self: center;
}

/* 房间信息横幅 */
.room-banner {
  align-self: center;
  text-align: center;
  padding: 4px 16px;
  margin: 0 0 8px;
  font-size: 11px;
  color: var(--text-muted);
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 20px;
}
.room-banner strong { color: var(--text-secondary); }

/* 消息卡片 - 远端（左侧） */
.msg-card {
  background: var(--bubble-other);
  border-radius: 6px 18px 18px 18px;
  padding: 10px 14px;
  cursor: pointer;
  transition: all var(--transition);
  animation: fadeIn .25s ease;
  word-break: break-word;
  overflow-wrap: break-word;
  font-size: 14px;
  line-height: 1.55;
  width: fit-content;
  max-width: 85%;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans SC", sans-serif;
  box-shadow: none;
  align-self: flex-start;
  position: relative;
}
.msg-card .msg-content { white-space: pre-wrap; }
.msg-card:hover { filter: brightness(.97); }
.msg-card.selected { filter: brightness(.93); box-shadow: 0 0 0 2px var(--accent-light); }
.msg-card.new-msg { animation: highlightIn .6s ease; }

.msg-card.local {
  align-self: flex-end;
  background: var(--bubble-self);
  color: var(--bubble-self-text);
  border: none;
  border-radius: 18px 6px 18px 18px;
}
.msg-card.local:hover { filter: brightness(.97); }
[data-theme=\\"dark\\"] .msg-card.local { background: var(--bubble-self); color: var(--bubble-self-text); }
[data-theme=\\"dark\\"] .msg-card.local:hover { filter: brightness(1.08); }

.msg-card.history-msg {
  background: #dce6f5;
  padding: 8px 14px;
  opacity: 1;
  box-shadow: none;
  border-radius: 6px 14px 14px 14px;
}
.msg-card.history-msg .msg-content {
  color: #1a3a7a;
  font-weight: 500;
}
[data-theme="dark"] .msg-card.history-msg {
  background: #1a2538;
}
[data-theme="dark"] .msg-card.history-msg .msg-content {
  color: #8aaff5;
}
.msg-card.history-msg.local {
  background: #c8e6d0;
  border-radius: 14px 6px 14px 14px;
}
.msg-card.history-msg.local .msg-content { color: #1a3a7a; }
[data-theme="dark"] .msg-card.history-msg.local {
  background: #1a2e24;
}
[data-theme="dark"] .msg-card.history-msg.local .msg-content { color: #8aaff5; }
.msg-card.history-msg .msg-meta { margin-top: 2px; font-size: 10px; }

.msg-card.image-card {
  padding: 3px;
  cursor: pointer;
  width: auto;
  max-width: 300px;
  border-radius: 16px;
  overflow: hidden;
}
.msg-card.image-card.local { border-radius: 16px; }
.msg-card.image-card.history-msg { max-width: 170px; }
.msg-card.image-card.history-msg .msg-image { max-height: 110px; }
.msg-card .msg-image {
  width: 100%;
  max-height: 240px;
  object-fit: cover;
  border-radius: 9px;
  display: block;
  cursor: zoom-in;
}
.msg-meta {
  display: none;
  font-size: 10px;
  color: var(--text-secondary);
  margin-top: 3px;
  gap: 6px;
  user-select: none;
}
.msg-card:hover .msg-meta {
  display: flex;
  justify-content: flex-start;
}
.msg-card.local:hover .msg-meta {
  justify-content: flex-end;
}
.image-card .msg-meta { padding: 0 6px 4px; }

@keyframes fadeIn { from { opacity: 0; transform: translateY(4px); } to { opacity: 1; transform: translateY(0); } }
@keyframes highlightIn {
  0% { filter: brightness(.92); transform: scale(1.01); }
  100% { filter: brightness(1); transform: scale(1); }
}

/* --- 历史折叠 --- */
.history-fold {
  width: 100%;
  text-align: center;
  padding: 4px 0;
  align-self: center;
}
.history-fold-btn {
  background: var(--surface);
  border: 1px solid var(--border);
  color: var(--text-muted);
  font-size: 11px;
  padding: 5px 16px;
  border-radius: 20px;
  cursor: pointer;
  font-family: inherit;
  transition: all var(--transition);
}
.history-fold-btn:hover { border-color: var(--accent); color: var(--accent); background: var(--accent-light); }
.history-section {
  display: none;
  flex-direction: column;
  align-items: flex-start;
  gap: 6px;
  width: 100%;
}
.history-section.show { display: flex; }
.history-sep {
  width: 100%;
  border: none;
  border-top: 1px solid var(--border);
  margin: 10px 0 6px;
  align-self: center;
}

/* --- 主题切换 --- */
.theme-btn {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  width: 32px; height: 32px;
  cursor: pointer;
  font-size: 15px;
  display: flex; align-items: center; justify-content: center;
  transition: all var(--transition);
  flex-shrink: 0;
}
.theme-btn:hover { border-color: var(--accent); background: var(--accent-light); transform: scale(1.05); }

.btn {
  padding: 9px 18px;
  border: none;
  border-radius: var(--radius-sm);
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  transition: all var(--transition);
  font-family: inherit;
  display: flex; align-items: center; gap: 6px;
  letter-spacing: .2px;
}
.btn:active { transform: scale(.97); }
.btn-primary {
  background: var(--accent-gradient);
  color: #fff;
  box-shadow: 0 2px 8px rgba(79,110,246,.3);
}
.btn-primary:hover { box-shadow: 0 4px 14px rgba(79,110,246,.4); transform: translateY(-1px); }
.btn-secondary {
  background: var(--bg);
  color: var(--text-secondary);
  border: 1px solid var(--border);
}
.btn-secondary:hover { background: var(--surface-hover); border-color: var(--accent); color: var(--accent); }
.btn-icon {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  width: 42px; height: 42px;
  display: flex; align-items: center; justify-content: center;
  cursor: pointer; font-size: 18px;
  transition: all var(--transition);
  flex-shrink: 0;
}
.btn-icon:hover { border-color: var(--accent); color: var(--accent); background: var(--accent-light); }

/* --- 底部输入区 --- */
.input-bar {
  background: var(--surface);
  border-top: 1px solid var(--border);
  padding: 10px 14px;
  display: flex;
  gap: 10px;
  align-items: flex-end;
  flex-shrink: 0;
}
.msg-textarea {
  flex: 1;
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 10px 14px;
  font-size: 13px;
  font-family: "SF Mono", "Fira Code", "Cascadia Code", Consolas, "Noto Sans SC", monospace;
  tab-size: 4;
  outline: none;
  transition: all var(--transition);
  background: var(--bg);
  color: var(--text);
  resize: none;
  line-height: 1.5;
  min-height: 42px;
  max-height: 200px;
  overflow-y: auto;
}
.msg-textarea:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-light);
  background: var(--surface);
}
.drop-zone {
  position: fixed; inset: 0; z-index: 300;
  display: none; align-items: center; justify-content: center;
  background: rgba(79,110,246,.06);
  backdrop-filter: blur(4px);
  border: 3px dashed var(--accent); margin: 24px; border-radius: 24px;
  pointer-events: none;
}
.drop-zone.active { display: flex; }
.drop-zone span { font-size: 22px; color: var(--accent); font-weight: 700; }

/* --- 加入页面 --- */
.join-overlay {
  position: fixed; inset: 0;
  background: var(--bg);
  display: flex; align-items: center; justify-content: center;
  z-index: 100;
}
.join-overlay::before {
  content: '';
  position: absolute;
  top: -120px; right: -120px;
  width: 400px; height: 400px;
  background: radial-gradient(circle, var(--accent-light) 0%, transparent 70%);
  border-radius: 50%;
  pointer-events: none;
}
.join-overlay::after {
  content: '';
  position: absolute;
  bottom: -80px; left: -80px;
  width: 300px; height: 300px;
  background: radial-gradient(circle, rgba(123,92,240,.08) 0%, transparent 70%);
  border-radius: 50%;
  pointer-events: none;
}
.join-card {
  background: var(--surface);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-lg);
  padding: 36px 32px;
  width: 400px;
  max-width: 92vw;
  text-align: center;
  position: relative;
  z-index: 1;
  border: 1px solid var(--border);
}
.join-card h1 {
  font-size: 30px;
  font-weight: 800;
  background: var(--accent-gradient);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom: 6px;
}
.join-card .subtitle { color: var(--text-muted); font-size: 14px; margin-bottom: 28px; }
.join-card label { display: block; text-align: left; font-size: 12px; font-weight: 600; margin-bottom: 5px; color: var(--text-secondary); text-transform: uppercase; letter-spacing: .5px; }
.join-card input, .join-card select {
  width: 100%; padding: 11px 14px; border: 1px solid var(--border); border-radius: var(--radius-sm);
  font-size: 14px; font-family: inherit; outline: none; margin-bottom: 16px; transition: all var(--transition);
  background: var(--bg); color: var(--text);
}
.join-card input:focus, .join-card select:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-light);
}
.join-card .btn { width: 100%; justify-content: center; padding: 13px; font-size: 15px; border-radius: var(--radius); }

/* --- Toast --- */
.toast {
  position: fixed; bottom: 28px; left: 50%; transform: translateX(-50%);
  background: var(--text); color: var(--bg); padding: 10px 22px; border-radius: var(--radius);
  font-size: 13px; z-index: 200; animation: toastIn .3s ease;
  pointer-events: none; font-weight: 500;
  box-shadow: var(--shadow-lg);
}
.toast.fadeout { animation: toastOut .25s ease forwards; }
@keyframes toastIn { from { opacity: 0; transform: translateX(-50%) translateY(12px); } to { opacity: 1; transform: translateX(-50%) translateY(0); } }
@keyframes toastOut { from { opacity: 1; } to { opacity: 0; } }

/* --- 图片灯箱 --- */
.lightbox {
  position: fixed; inset: 0; background: rgba(0,0,0,.9); z-index: 400;
  display: none; align-items: center; justify-content: center; cursor: pointer;
  backdrop-filter: blur(8px);
  animation: fadeIn .2s ease;
}
.lightbox.show { display: flex; }
.lightbox img { max-width: 92vw; max-height: 92vh; border-radius: var(--radius); box-shadow: 0 12px 48px rgba(0,0,0,.5); }

/* --- 响应式 --- */
@media (max-width: 768px) {
  .main { flex-direction: column; }
  .header { padding: 8px 14px; gap: 8px; }
  .room-token { max-width: 80px; font-size: 10px; }
  .msg-card { max-width: 85%; font-size: 14px; }
  .msg-card.image-card { max-width: 240px; }
  .msg-textarea { font-size: 15px; }
  .header-right .online-count { display: none; }
  .header-right .status-badge { display: none; }
}
@media (min-width: 769px) and (max-width: 1024px) {
  .msg-card { max-width: 70%; }
}
@media (min-width: 1025px) {
  .msg-card { max-width: 60%; }
}
</style>
</head>
<body>

<!-- 图片灯箱 -->
<div class="lightbox" id="lightbox"><img id="lightboxImg" alt=""></div>

<!-- 拖放区域 -->
<div class="drop-zone" id="dropZone"><span>释放以发送图片</span></div>

<!-- 加入房间覆盖层 -->
<div class="join-overlay" id="joinOverlay" style="display:none">
  <div class="join-card">
    <h1>ClipRelay</h1>
    <p class="subtitle">跨设备文本接力 · 30分钟临时房间</p>
    <label for="tokenInput">房间令牌</label>
    <input type="text" id="tokenInput" placeholder="输入房间令牌或粘贴链接…" autocomplete="off">
    <label for="deviceSelect">设备类型</label>
    <select id="deviceSelect">
      <option value="desktop">桌面端</option>
      <option value="mobile">手机端</option>
      <option value="tablet">平板端</option>
    </select>
    <button class="btn btn-primary" id="joinBtn">进入房间</button>
  </div>
</div>

<!-- 主界面 -->
<div class="header" id="header" style="display:none">
  <div class="header-left">
    <span class="logo">ClipRelay</span>
    <span class="room-token" id="roomTokenDisplay" title="房间令牌"></span>
  </div>
  <div class="header-right">
    <button class="btn btn-secondary btn-sm" id="clearBtn2" style="display:none" title="清空消息">清空</button>
    <span class="online-count"><span class="online-dot"></span><span id="onlineCount">0</span> 在线</span>
    <span class="status-badge active" id="statusBadge">活跃</span>
    <button class="theme-btn" id="themeBtn" title="切换主题">🌙</button>
  </div>
</div>

<div class="main" id="main" style="display:none">
  <div class="panel-messages">
    <div class="msg-list" id="msgList">
      <div class="room-banner" id="roomBanner" style="display:none"></div>
      <div class="history-fold" id="historyFold"></div>
      <div class="history-section" id="historySection"></div>
    </div>
    <div class="input-bar">
      <textarea class="msg-textarea" id="msgInput" placeholder="输入消息" rows="1" autocomplete="off"></textarea>
      <button class="btn-icon" id="imgBtn" title="发送图片">🖼</button>
      <input type="file" id="imgInput" accept="image/*" style="display:none">
      <a href="https://upfile.live/zh-cn/" target="_blank" rel="noopener" class="btn-icon" id="fileBtn" title="文件传送（第三方）">📎</a>
      <button class="btn btn-primary" id="sendBtn">发送</button>
    </div>
  </div>

  </div>

<script>
(function() {
  const $ = (sel) => document.querySelector(sel);
  const $$ = (sel) => document.querySelectorAll(sel);

  const joinOverlay = $('#joinOverlay');
  const tokenInput = $('#tokenInput');
  const deviceSelect = $('#deviceSelect');
  const joinBtn = $('#joinBtn');
  const header = $('#header');
  const main = $('#main');
  const roomTokenDisplay = $('#roomTokenDisplay');
  const onlineCountEl = $('#onlineCount');
  const statusBadge = $('#statusBadge');
  const msgList = $('#msgList');
  const historyFold = $('#historyFold');
  const historySection = $('#historySection');
  const roomBanner = $('#roomBanner');
  const msgInput = $('#msgInput');
  const sendBtn = $('#sendBtn');
  const imgBtn = $('#imgBtn');
  const imgInput = $('#imgInput');
  const themeBtn = $('#themeBtn');
  const clearBtn2 = $('#clearBtn2');
  const lightbox = $('#lightbox');
  const lightboxImg = $('#lightboxImg');
  const dropZone = $('#dropZone');

  // --- 状态 ---
  let ws = null;
  let token = '';
  let deviceType = 'desktop';
  let selectedMsgId = null;
  let defaultToken = '';

  // --- 设备检测 ---
  function detectDevice() {
    const ua = navigator.userAgent;
    const isMobile = /Mobi|Android|iPhone/i.test(ua);
    const isTablet = /iPad|Tablet|PlayBook/i.test(ua) || (isMobile && window.innerWidth >= 768);
    if (isTablet) return 'tablet';
    if (isMobile) return 'mobile';
    return 'desktop';
  }

  // --- Toast ---
  function showToast(text) {
    const existing = document.querySelector('.toast');
    if (existing) existing.remove();
    const el = document.createElement('div');
    el.className = 'toast';
    el.textContent = text;
    document.body.appendChild(el);
    setTimeout(() => { el.classList.add('fadeout'); setTimeout(() => el.remove(), 300); }, 2000);
  }

  // --- 剪贴板 ---
  async function copyToClipboard(text) {
    // 方案1: Clipboard API（无需用户手势，自动复制/点击都可用）
    if (navigator.clipboard && navigator.clipboard.writeText) {
      try { await navigator.clipboard.writeText(text); return true; } catch (_) {}
    }
    // 方案2: execCommand（同步，需要页面焦点）
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.cssText = 'position:fixed;top:0;left:0;width:2px;height:2px;opacity:0;pointer-events:none;z-index:-1;';
    document.body.appendChild(ta);
    ta.select();
    ta.setSelectionRange(0, 999999);
    let ok = false;
    try { ok = document.execCommand('copy'); } catch (_) {}
    ta.remove();
    return ok;
  }


  // --- WebSocket ---
  function connect() {
    const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:';
    const wsUrl = \`\${protocol}//\${location.host}/?token=\${encodeURIComponent(token)}\`;

    ws = new WebSocket(wsUrl);

    ws.onopen = () => {
      ws.send(JSON.stringify({ type: 'join', device_type: deviceType }));
    };

    ws.onmessage = (event) => {
      let data;
      try { data = JSON.parse(event.data); } catch { return; }
      handleMessage(data);
    };

    ws.onclose = (event) => {
      if (event.code === 4001) {
        handleExpired();
      } else if (event.code !== 4003) {
        setTimeout(() => { if (!ws || ws.readyState > 1) connect(); }, 3000);
      }
    };

    ws.onerror = () => {};
  }

  // --- 桌面通知 ---
  function requestNotificationPermission() {
    if (!('Notification' in window)) return;
    if (Notification.permission === 'default') {
      Notification.requestPermission();
    }
  }

  // 兜底：首次用户交互时请求通知权限（适用于 URL 直连跳过加入页的情况）
  function installDelayedPermissionRequest() {
    if (!('Notification' in window)) return;
    if (Notification.permission !== 'default') return;
    const handler = () => {
      Notification.requestPermission();
      document.removeEventListener('click', handler);
      document.removeEventListener('keydown', handler);
    };
    document.addEventListener('click', handler);
    document.addEventListener('keydown', handler);
  }

  function showDesktopNotification(msg) {
    if (!('Notification' in window)) return;
    if (Notification.permission !== 'granted') return;
    // 只在页面不可见时弹通知
    if (!document.hidden) return;

    const isImage = msg.msg_type === 'image';
    const title = 'ClipRelay · 新消息';
    const body = isImage ? '[图片]' : (msg.content.length > 120 ? msg.content.slice(0, 120) + '…' : msg.content);
    const n = new Notification(title, {
      body,
      icon: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="20" fill="%234f6ef6"/><text x="50" y="68" font-size="50" text-anchor="middle" fill="white">📋</text></svg>',
      tag: 'clip-relay-msg',
      renotify: true,
    });
    n.onclick = () => {
      window.focus();
      n.close();
    };
    setTimeout(() => n.close(), 5000);
  }

  function handleMessage(data) {
    switch (data.type) {
      case 'joined': {
        // 清空列表和折叠区
        msgList.querySelectorAll('.msg-card').forEach(c => c.remove());
        historySection.innerHTML = '';
        historyFold.innerHTML = '';

        // 显示房间信息横幅
        if (data.room_name) {
          roomBanner.innerHTML = '<strong>' + escapeHtml(data.room_name) + '</strong>';
        } else {
          roomBanner.innerHTML = '房间';
        }
        roomBanner.style.display = '';

        if (data.messages.length > 0) {
          // 历史消息放入折叠区
          for (const m of data.messages) {
            appendMessageCard(m, false, historySection);
          }
          // 显示折叠按钮
          historyFold.innerHTML = \`<hr class="history-sep"><button class="history-fold-btn" id="historyToggle">展开历史消息 (\${data.messages.length}条)</button>\`;
          const toggleBtn = historyFold.querySelector('#historyToggle');
          toggleBtn.addEventListener('click', () => {
            const show = historySection.classList.toggle('show');
            toggleBtn.textContent = show
              ? \`收起历史消息 (\${data.messages.length}条)\`
              : \`展开历史消息 (\${data.messages.length}条)\`;
          });
        }
        scrollToBottom();
        updateRoomStatus(data.expires_in, data.online_count);
        if (data.permanent) {
          statusBadge.textContent = '永久';
          statusBadge.className = 'status-badge active';
        } else {
          startCountdown(data.expires_in);
        }
        // 显示清空按钮
        clearBtn2.style.display = '';
        break;
      }

      case 'message':
      case 'image': {
        const m = data.message;
        appendMessageCard(m, true);
        selectedMsgId = m.id;
        highlightSelectedCard();
        showDesktopNotification(m);
        break;
      }

      case 'device_joined': {
        showToast(\`\${deviceLabel(data.device_type)} 加入了房间\`);
        break;
      }

      case 'device_left': {
        showToast(\`\${deviceLabel(data.device_type)} 离开了房间\`);
        break;
      }

      case 'room_expired': {
        handleExpired();
        break;
      }

      case 'messages_cleared': {
        msgList.querySelectorAll('.msg-card').forEach(c => c.remove());
        historySection.innerHTML = '';
        historyFold.innerHTML = '';
        roomBanner.style.display = '';
        showToast('消息已清空');
        break;
      }

      case 'error': {
        showToast(\`错误: \${data.message}\`);
        break;
      }
    }
  }

function appendMessageCard(msg, isNew, container) {
    const target = container || msgList;
    const isHistory = target === historySection;
    const card = document.createElement('div');
    const isImage = msg.msg_type === 'image';
    card.className = 'msg-card'
      + (isNew ? ' new-msg' : '')
      + (isHistory ? ' history-msg' : '')
      + (isImage ? ' image-card' : '');
    card.dataset.msgId = msg.id;
    card.dataset.msgType = msg.msg_type || 'text';

    if (isImage) {
      card.innerHTML = \`
        <img class="msg-image" src="\${escapeAttr(msg.content)}" alt="图片" loading="lazy">
        <div class="msg-meta">
          <span>\${formatTime(msg.created_at)}</span>
          <span>图片 #\${msg.id}</span>
        </div>\`;
      card.querySelector('.msg-image').addEventListener('click', (e) => {
        e.stopPropagation();
        lightboxImg.src = msg.content;
        lightbox.classList.add('show');
      });
    } else {
      card.innerHTML = \`
        <div class="msg-content">\${escapeHtml(msg.content)}</div>
        <div class="msg-meta">
          <span>\${formatTime(msg.created_at)}</span>
          <span>#\${msg.id}</span>
        </div>\`;
    }

    let _touched = false;

    card.addEventListener('touchend', () => {
      const sel = window.getSelection().toString().trim();
      if (sel && msg.msg_type !== 'image') {
        _touched = true;
        setTimeout(() => { copyToClipboard(sel); showToast('已复制'); }, 10);
      }
    });

    card.addEventListener('click', () => {
      if (msg.msg_type === 'image' || _touched) { _touched = false; return; }
      const sel = window.getSelection().toString().trim();
      copyToClipboard(sel || msg.content);
      showToast('已复制');
    });

    target.appendChild(card);

    if (isNew) {
      scrollToBottom();
    }
  }

  function highlightSelectedCard() {
    $$('.msg-card').forEach(c => c.classList.remove('selected'));
    const card = document.querySelector(\`.msg-card[data-msg-id="\${selectedMsgId}"]\`);
    if (card) card.classList.add('selected');
  }

  function scrollToBottom() {
    msgList.scrollTop = msgList.scrollHeight;
  }

  function updateRoomStatus(expiresIn, onlineCount) {
    onlineCountEl.textContent = onlineCount;

    if (expiresIn === -1) {
      // 永久房间，不更新（由 joined 处理）
      return;
    }
    if (expiresIn <= 0) {
      statusBadge.textContent = '已过期';
      statusBadge.className = 'status-badge expired';
    } else if (expiresIn < 300) {
      statusBadge.textContent = formatDuration(expiresIn);
      statusBadge.className = 'status-badge expiring';
    } else {
      statusBadge.textContent = formatDuration(expiresIn);
      statusBadge.className = 'status-badge active';
    }
  }

  function handleExpired() {
    statusBadge.textContent = '已过期';
    statusBadge.className = 'status-badge expired';
    showToast('房间已过期（30分钟）');
    msgInput.disabled = true;
    sendBtn.disabled = true;
    imgBtn.disabled = true;
    if (ws) ws.close();
  }

  // --- 发送消息 ---
  function sendMessage() {
    const content = msgInput.value.trim();
    if (!content) return;
    if (!ws || ws.readyState !== 1) {
      showToast('未连接到房间');
      return;
    }
    ws.send(JSON.stringify({ type: 'message', content }));
    appendLocalMessage(content, 'text');
    msgInput.value = '';
    msgInput.style.height = '';
    msgInput.focus();
  }

  function sendImage(dataUrl, filename) {
    if (!ws || ws.readyState !== 1) {
      showToast('未连接到房间');
      return;
    }
    ws.send(JSON.stringify({ type: 'image', content: dataUrl, filename: filename || 'image.png' }));
    appendLocalMessage(dataUrl, 'image', filename);
  }

  function appendLocalMessage(content, msgType, filename) {
    const card = document.createElement('div');
    const isImage = msgType === 'image';
    card.className = 'msg-card local' + (isImage ? ' image-card' : '');
    card.dataset.local = 'true';
    card.dataset.msgType = msgType;
    const now = new Date().toISOString();

    if (isImage) {
      card.innerHTML = \`
        <img class="msg-image" src="\${escapeAttr(content)}" alt="图片" loading="lazy">
        <div class="msg-meta">
          <span>\${formatTime(now)}</span>
          <span>本地图片</span>
        </div>\`;
      card.querySelector('.msg-image').addEventListener('click', (e) => {
        e.stopPropagation();
        lightboxImg.src = content;
        lightbox.classList.add('show');
      });
    } else {
      card.innerHTML = \`
        <div class="msg-content">\${escapeHtml(content)}</div>
        <div class="msg-meta">
          <span>\${formatTime(now)}</span>
          <span>本地</span>
        </div>\`;
    }

    let _touched = false;

    card.addEventListener('touchend', () => {
      const sel = window.getSelection().toString().trim();
      if (sel && msgType !== 'image') {
        _touched = true;
        setTimeout(() => { copyToClipboard(sel); showToast('已复制'); }, 10);
      }
    });

    card.addEventListener('click', () => {
      if (msgType === 'image' || _touched) { _touched = false; return; }
      const sel = window.getSelection().toString().trim();
      copyToClipboard(sel || content);
      showToast('已复制');
    });
    msgList.appendChild(card);
    scrollToBottom();
  }

  // --- 图片处理 ---
  function handleImageFile(file) {
    if (!file || !file.type.startsWith('image/')) {
      showToast('仅支持图片文件');
      return;
    }
    const reader = new FileReader();
    reader.onload = () => {
      sendImage(reader.result, file.name);
    };
    reader.readAsDataURL(file);
  }

  // --- 倒计时 ---
  let countdownInterval = null;
  function startCountdown(initialSeconds) {
    let remaining = initialSeconds;
    if (countdownInterval) clearInterval(countdownInterval);
    countdownInterval = setInterval(() => {
      remaining--;
      if (remaining <= 0) {
        clearInterval(countdownInterval);
        updateRoomStatus(0, parseInt(onlineCountEl.textContent) || 0);
        handleExpired();
      } else {
        updateRoomStatus(remaining, parseInt(onlineCountEl.textContent) || 0);
      }
    }, 1000);
  }

  // --- 工具函数 ---
  function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  function escapeAttr(str) {
    return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function formatTime(iso) {
    const d = new Date(iso);
    const pad = (n) => String(n).padStart(2, '0');
    return \`\${pad(d.getHours())}:\${pad(d.getMinutes())}:\${pad(d.getSeconds())}\`;
  }

  function formatDuration(seconds) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return \`\${m}分\${s}秒\`;
  }

  function deviceLabel(type) {
    return { mobile: '手机', tablet: '平板', desktop: '桌面' }[type] || type;
  }

  // --- 事件绑定 ---
  joinBtn.addEventListener('click', () => {
    const input = tokenInput.value.trim() || defaultToken || 'clip-relay';
    token = input;
    deviceType = deviceSelect.value;
    roomTokenDisplay.textContent = token;
    joinOverlay.style.display = 'none';
    header.style.display = '';
    main.style.display = '';
    requestNotificationPermission();
    connect();
  });

  tokenInput.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') joinBtn.click();
  });

  sendBtn.addEventListener('click', sendMessage);
  msgInput.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });
  // 输入框自适应高度
  msgInput.addEventListener('input', () => {
    msgInput.style.height = '';
    msgInput.style.height = Math.min(msgInput.scrollHeight, 200) + 'px';
  });

  // 粘贴图片
  msgInput.addEventListener('paste', (e) => {
    const items = e.clipboardData?.items;
    if (!items) return;
    for (const item of items) {
      if (item.type.startsWith('image/')) {
        e.preventDefault();
        handleImageFile(item.getAsFile());
        return;
      }
    }
  });

  // 图片按钮
  imgBtn.addEventListener('click', () => imgInput.click());
  imgInput.addEventListener('change', () => {
    if (imgInput.files[0]) {
      handleImageFile(imgInput.files[0]);
      imgInput.value = '';
    }
  });

  // 拖放图片
  let dragCounter = 0;
  document.addEventListener('dragenter', (e) => {
    e.preventDefault();
    dragCounter++;
    if (dragCounter === 1) dropZone.classList.add('active');
  });
  document.addEventListener('dragleave', () => {
    dragCounter--;
    if (dragCounter === 0) dropZone.classList.remove('active');
  });
  document.addEventListener('dragover', (e) => e.preventDefault());
  document.addEventListener('drop', (e) => {
    e.preventDefault();
    dragCounter = 0;
    dropZone.classList.remove('active');
    const files = e.dataTransfer?.files;
    if (files && files[0]) handleImageFile(files[0]);
  });

  // 灯箱关闭
  lightbox.addEventListener('click', () => lightbox.classList.remove('show'));

  // --- 主题切换 ---
  function applyTheme(dark) {
    document.documentElement.setAttribute('data-theme', dark ? 'dark' : '');
    themeBtn.textContent = dark ? '☀️' : '🌙';
    try { localStorage.setItem('clip-relay-theme', dark ? 'dark' : 'light'); } catch (_) {}
  }

  clearBtn2.addEventListener('click', () => {
    if (!ws || ws.readyState !== 1) return;
    if (confirm('确定清空当前房间所有消息？')) {
      ws.send(JSON.stringify({ type: 'clear_messages' }));
    }
  });

  themeBtn.addEventListener('click', () => {
    const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
    applyTheme(!isDark);
  });

  // --- 初始化 ---
  async function init() {
    deviceSelect.value = detectDevice();

    // 同步检查 URL token（不等异步请求）
    const params = new URLSearchParams(location.search);
    let urlToken = params.get('token');
    if (!urlToken && location.hash) {
      urlToken = location.hash.slice(1);
    }

    if (urlToken) {
      // 有 token → 直接进入房间
      token = urlToken;
      deviceType = deviceSelect.value;
      roomTokenDisplay.textContent = token;
      header.style.display = '';
      main.style.display = '';
      connect();
      return;
    }

    // 无 token → 获取配置后显示加入页面
    try {
      const resp = await fetch('/api/config');
      const cfg = await resp.json();
      if (cfg.defaultToken) defaultToken = cfg.defaultToken;
    } catch (_) {}

    tokenInput.value = defaultToken || '';
    joinOverlay.style.display = '';
  }

  init();
})();
</script>
</body>
</html>
`;
export const ADMIN_HTML: string = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="color-scheme" content="dark light">
<title>房间管理 · ClipRelay</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}

:root{
  color-scheme:light;
  --bg:#f2f3f7;--surface:#fff;--border:#e4e7ed;--text:#1e1f24;
  --text-secondary:#868b96;--text-muted:#b0b5bf;
  --accent:#4f6ef6;--accent-hover:#3d5de0;--accent-light:#eef1fe;
  --accent-gradient:linear-gradient(135deg,#4f6ef6 0%,#7b5cf0 100%);
  --danger:#ef4444;--success:#10b981;--warning:#f59e0b;
  --radius:10px;--radius-sm:6px;
  --shadow:0 2px 8px rgba(0,0,0,.06);--shadow-lg:0 8px 24px rgba(0,0,0,.08);
  --transition:.2s cubic-bezier(.4,0,.2,1);
}
[data-theme="dark"]{
  color-scheme:dark;
  --bg:#0d0f14;--surface:#161820;--border:#282b35;--text:#e3e5ec;
  --text-secondary:#8d919e;--text-muted:#5e6270;
  --accent:#6b8af7;--accent-hover:#8ba4f9;--accent-light:#1a2040;
  --danger:#f87171;--success:#34d399;--warning:#fbbf24;
  --shadow:0 2px 8px rgba(0,0,0,.3);--shadow-lg:0 8px 24px rgba(0,0,0,.4);
}

body{
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Noto Sans SC",sans-serif;
  background:var(--bg);color:var(--text);min-height:100vh;
  -webkit-font-smoothing:antialiased;
}

.container{max-width:1000px;margin:0 auto;padding:24px 20px 120px}

.header{
  display:flex;align-items:center;justify-content:space-between;
  margin-bottom:28px;flex-wrap:wrap;gap:12px;
}
.header h1{
  font-size:24px;font-weight:800;
  background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;
}
.header-actions{display:flex;gap:10px;align-items:center;}

.btn{
  padding:8px 18px;border:none;border-radius:var(--radius-sm);font-size:13px;
  font-weight:600;cursor:pointer;transition:all var(--transition);font-family:inherit;
}
.btn:active{transform:scale(.97)}
.btn-primary{background:var(--accent-gradient);color:#fff;box-shadow:0 2px 8px rgba(79,110,246,.25)}
.btn-primary:hover{box-shadow:0 4px 14px rgba(79,110,246,.35);transform:translateY(-1px)}
.btn-danger{background:var(--danger);color:#fff}
.btn-danger:hover{background:#dc2626}
.btn-secondary{background:var(--bg);color:var(--text-secondary);border:1px solid var(--border)}
.btn-secondary:hover{border-color:var(--accent);color:var(--accent)}
.btn-sm{padding:5px 12px;font-size:12px}

/* 登录页 */
.login-overlay{
  position:fixed;inset:0;background:var(--bg);display:flex;
  align-items:center;justify-content:center;z-index:1000;
}
.login-card{
  background:var(--surface);border-radius:var(--radius);padding:36px 32px;
  width:360px;max-width:92vw;text-align:center;
  box-shadow:var(--shadow-lg);border:1px solid var(--border);
}
.login-card h1{
  font-size:26px;font-weight:800;margin-bottom:4px;
  background:var(--accent-gradient);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;
}
.login-card .sub{color:var(--text-muted);font-size:14px;margin-bottom:24px}
.login-card label{display:block;text-align:left;font-size:12px;font-weight:600;color:var(--text-secondary);margin-bottom:5px;text-transform:uppercase;letter-spacing:.3px}
.login-card input{
  width:100%;padding:11px 14px;border:1px solid var(--border);border-radius:var(--radius-sm);
  font-size:14px;font-family:inherit;outline:none;margin-bottom:16px;
  background:var(--bg);color:var(--text);transition:border-color var(--transition);
}
.login-card input:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-light)}
.login-card .btn{width:100%;justify-content:center;padding:12px;font-size:15px;border-radius:var(--radius)}
.login-error{
  color:var(--danger);font-size:13px;margin-top:12px;
  background:#fef2f2;padding:10px 14px;border-radius:var(--radius-sm);
  border:1px solid #fecaca;display:none;
}
.login-error.show{display:block}
[data-theme="dark"] .login-error{background:#450a0a;border-color:#7f1d1d}

/* 密码可见切换 */
.pwd-wrap{position:relative;margin-bottom:16px}
.pwd-wrap input{margin-bottom:0!important}
.pwd-toggle{
  position:absolute;right:12px;top:50%;transform:translateY(-50%);
  background:none;border:none;cursor:pointer;font-size:16px;color:var(--text-muted);
  padding:4px;font-family:inherit;line-height:1;
}
.pwd-toggle:hover{color:var(--text)}

/* 修改密码卡片 */
.pwd-card{
  background:var(--surface);border:1px solid var(--border);
  border-radius:var(--radius);padding:20px 24px;margin-bottom:24px;
  box-shadow:var(--shadow);
}
.pwd-card h2{font-size:16px;margin-bottom:14px;color:var(--text-secondary)}
.pwd-row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap}
.pwd-group{display:flex;flex-direction:column;gap:5px}
.pwd-group label{font-size:12px;font-weight:600;color:var(--text-secondary);text-transform:uppercase;letter-spacing:.3px}
.pwd-group input{
  padding:9px 12px;border:1px solid var(--border);border-radius:var(--radius-sm);
  font-size:14px;font-family:inherit;outline:none;width:180px;
  background:var(--bg);color:var(--text);transition:border-color var(--transition);
}
.pwd-group input:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-light)}

/* 创建表单 */
.create-card{
  background:var(--surface);border:1px solid var(--border);
  border-radius:var(--radius);padding:20px 24px;margin-bottom:24px;
  box-shadow:var(--shadow);
}
.create-card h2{font-size:16px;margin-bottom:14px;color:var(--text-secondary)}
.form-row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap}
.form-group{display:flex;flex-direction:column;gap:5px}
.form-group label{font-size:12px;font-weight:600;color:var(--text-secondary);text-transform:uppercase;letter-spacing:.3px}
.form-group input,.form-group select{
  padding:9px 12px;border:1px solid var(--border);border-radius:var(--radius-sm);
  font-size:14px;font-family:inherit;outline:none;background:var(--bg);color:var(--text);
  transition:border-color var(--transition);
}
.form-group input:focus,.form-group select:focus{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-light)}
.form-group input{width:220px}
.form-group select{width:150px}

/* 房间列表 */
.room-table{
  width:100%;border-collapse:collapse;
  background:var(--surface);border-radius:var(--radius);
  overflow:hidden;box-shadow:var(--shadow);border:1px solid var(--border);
}
.room-table th,.room-table td{
  text-align:left;padding:12px 16px;font-size:13px;
  border-bottom:1px solid var(--border);
}
.room-table th{background:var(--bg);font-weight:600;color:var(--text-secondary);font-size:11px;text-transform:uppercase;letter-spacing:.3px}
.room-table tbody tr:hover{background:var(--accent-light)}
.room-table .token{font-family:"SF Mono","Fira Code",monospace;font-size:12px;color:var(--accent)}
.room-table .badge{
  display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:600;
}
.badge-permanent{background:#ecfdf5;color:#059669}
.badge-temp{background:#fffbeb;color:#d97706}
[data-theme="dark"] .badge-permanent{background:#064e3b;color:#34d399}
[data-theme="dark"] .badge-temp{background:#451a03;color:#fbbf24}
.room-table .actions{display:flex;gap:6px}
.room-table .row-disabled{opacity:.5;background:var(--bg)!important}
.room-table .row-disabled:hover{opacity:.7}
.btn-success{background:var(--success);color:#fff}
.btn-success:hover{background:#059669}

/* 复制链接弹窗 */
.copy-popover{
  position:fixed;z-index:999;background:var(--surface);border:1px solid var(--border);
  border-radius:var(--radius);box-shadow:var(--shadow-lg);padding:8px 0;min-width:220px;
  animation:fadeIn .15s ease;
}
.copy-popover button{
  display:block;width:100%;padding:10px 16px;border:none;background:none;
  text-align:left;font-size:13px;font-family:inherit;cursor:pointer;color:var(--text);
  transition:background var(--transition);
}
.copy-popover button:hover{background:var(--accent-light);color:var(--accent)}
.copy-popover button small{display:block;font-size:11px;color:var(--text-muted);margin-top:1px}
.copy-popover .divider{border-top:1px solid var(--border);margin:4px 0}
@keyframes fadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}

/* 域名状态 */
.domain-status{
  display:inline-flex;align-items:center;gap:4px;font-size:12px;padding:2px 8px;
  border-radius:20px;font-weight:500;
}
.domain-status.set{background:#ecfdf5;color:#059669}
.domain-status.unset{background:var(--bg);color:var(--text-muted)}
[data-theme="dark"] .domain-status.set{background:#064e3b;color:#34d399}

.toast{
  position:fixed;bottom:24px;left:50%;transform:translateX(-50%);
  background:var(--text);color:var(--bg);padding:8px 18px;border-radius:var(--radius);
  font-size:13px;font-weight:500;z-index:100;box-shadow:var(--shadow-lg);
}

@media(max-width:700px){
  .form-row,.pwd-row{flex-direction:column}
  .form-group input,.form-group select,.pwd-group input{width:100%}
  .room-table{font-size:11px}
  .room-table th,.room-table td{padding:8px 10px}
}
</style>
</head>
<body>

<!-- 登录页 -->
<div class="login-overlay" id="loginOverlay">
  <div class="login-card">
    <h1>ClipRelay</h1>
    <p class="sub">管理后台 · 请输入密码</p>
    <label for="loginPwd">密码</label>
    <div class="pwd-wrap">
      <input type="password" id="loginPwd" placeholder="默认密码 admin" autocomplete="current-password" style="padding-right:40px">
      <button type="button" class="pwd-toggle" id="pwdToggle" title="显示密码">👁</button>
    </div>
    <button class="btn btn-primary" id="loginBtn">登录</button>
    <p class="login-error" id="loginError"></p>
    <p style="font-size:12px;color:var(--accent);margin-top:16px;cursor:pointer;text-decoration:underline" id="forgotPwd" onclick="this.style.display='none';document.getElementById('recoveryHint').style.display='block'">忘记密码？</p>
    <p id="recoveryHint" style="display:none;font-size:12px;color:var(--text-secondary);margin-top:8px;background:var(--bg);padding:12px 14px;border-radius:6px;text-align:left;line-height:1.7">🔑 使用 <strong>RESET_KEY</strong> 进行登录，成功后密码将强制重置为 <strong>admin</strong>。<br><br>📌 获取 RESET_KEY：<br>· 本地/Docker：查看 <code>config/config.json</code> 中的 <code>resetKey</code> 字段<br>· Cloudflare：前往 Dashboard → Workers 和 Pages → 当前部署的 page → 查看部署 → 设置 → 变量和机密 → <code>RESET_KEY</code></p>
  </div>
</div>

<!-- 主界面 -->
<div class="container" id="mainPanel" style="display:none">

<div class="header">
  <h1>ClipRelay 管理后台</h1>
  <div class="header-actions">
    <a href="/" class="btn btn-secondary" style="text-decoration:none">← 返回首页</a>
    <button class="btn btn-secondary btn-sm" id="logoutBtn">退出</button>
    <button class="btn btn-secondary btn-sm" id="themeBtn" title="切换主题">🌙</button>
  </div>
</div>

<!-- 域名设置 -->
<div class="pwd-card">
  <h2>域名设置 <span class="domain-status unset" id="domainStatus">未配置</span></h2>
  <div class="pwd-row">
    <div class="pwd-group">
      <label>公网域名（用于生成外网链接）</label>
      <input type="text" id="domainInput" placeholder="例如：relay.yourdomain.com" autocomplete="off" style="width:300px">
    </div>
    <button class="btn btn-primary btn-sm" id="saveDomainBtn">保存域名</button>
  </div>
</div>

<!-- 修改密码 -->
<div class="pwd-card">
  <h2>修改密码</h2>
  <div class="pwd-row">
    <div class="pwd-group">
      <label>原密码</label>
      <input type="password" id="oldPwd" placeholder="输入原密码" autocomplete="off">
    </div>
    <div class="pwd-group">
      <label>新密码</label>
      <input type="password" id="newPwd" placeholder="输入新密码" autocomplete="off">
    </div>
    <button class="btn btn-secondary" id="changePwdBtn">修改密码</button>
  </div>
</div>

<!-- 创建房间 -->
<div class="create-card">
  <h2>创建新房间</h2>
  <div class="form-row">
    <div class="form-group">
      <label>房间名称</label>
      <input type="text" id="roomName" placeholder="例如：我的工作区" autocomplete="off">
    </div>
    <div class="form-group">
      <label>自定义令牌（可选）</label>
      <input type="text" id="roomToken" placeholder="留空自动生成" autocomplete="off">
    </div>
    <div class="form-group">
      <label>有效期</label>
      <select id="roomTTL">
        <option value="2">2 分钟（测试）</option>
        <option value="5">5 分钟</option>
        <option value="30">30 分钟（临时）</option>
        <option value="60">1 小时</option>
        <option value="120">2 小时</option>
        <option value="1440">24 小时</option>
        <option value="0">永久有效</option>
        <option value="-1">自定义</option>
      </select>
      <div id="customTTLField" style="display:none;margin-top:8px">
        <input type="number" id="customTTL" min="1" value="10" style="width:100px">
        <span style="font-size:12px;color:var(--text-muted)"> 分钟</span>
      </div>
    </div>
    <button class="btn btn-primary" id="createBtn">创建房间</button>
  </div>
</div>

<!-- 房间列表 -->
<table class="room-table">
  <thead>
    <tr>
      <th>房间名称</th>
      <th>令牌</th>
      <th>有效期</th>
      <th>消息数</th>
      <th>在线</th>
      <th>创建时间</th>
      <th>过期时间</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody id="roomList"><tr><td colspan="8" style="text-align:center;color:var(--text-muted);padding:32px">加载中…</td></tr></tbody>
</table>

</div>

<script>
(function(){
  const $=s=>document.querySelector(s);

  const loginOverlay=$('#loginOverlay');
  const loginPwd=$('#loginPwd');
  const loginBtn=$('#loginBtn');
  const loginError=$('#loginError');
  const pwdToggle=$('#pwdToggle');
  const mainPanel=$('#mainPanel');
  const roomName=$('#roomName');
  const roomToken=$('#roomToken');
  const roomTTL=$('#roomTTL');
  const createBtn=$('#createBtn');
  const roomList=$('#roomList');
  const themeBtn=$('#themeBtn');
  const logoutBtn=$('#logoutBtn');
  const oldPwd=$('#oldPwd');
  const newPwd=$('#newPwd');
  const changePwdBtn=$('#changePwdBtn');
  const domainStatus=$('#domainStatus');

  const domainInput=$('#domainInput');
  const saveDomainBtn=$('#saveDomainBtn');

  let serverConfig = { domain: '', lanIP: '' };

  let sessionToken = sessionStorage.getItem('clip-relay-admin-token') || '';

  // 主题
  function applyTheme(dark){
    document.documentElement.setAttribute('data-theme',dark?'dark':'');
    themeBtn.textContent=dark?'☀️':'🌙';
    try{localStorage.setItem('clip-relay-theme',dark?'dark':'light')}catch(_){}
  }
  const saved=(()=>{try{return localStorage.getItem('clip-relay-theme')}catch(_){return null}})();
  const prefers=window.matchMedia('(prefers-color-scheme:dark)').matches;
  applyTheme(saved==='dark'||(!saved&&prefers));
  themeBtn.addEventListener('click',()=>{
    applyTheme(document.documentElement.getAttribute('data-theme')!=='dark');
  });

  function toast(text){
    const e=document.querySelector('.toast');
    if(e)e.remove();
    const el=document.createElement('div');
    el.className='toast';el.textContent=text;
    document.body.appendChild(el);
    setTimeout(()=>el.remove(),2000);
  }

  function api(path, opts={}){
    const headers={...opts.headers,'Authorization':'Bearer '+sessionToken};
    if(opts.body&&typeof opts.body==='object'){
      headers['Content-Type']='application/json';
      opts.body=JSON.stringify(opts.body);
    }
    return fetch(path,{...opts,headers});
  }

  // 检查登录状态
  async function checkAuth(){
    if(!sessionToken){
      showLogin();
      return false;
    }
    try{
      const resp=await api('/api/admin/rooms');
      if(resp.status===401){sessionToken='';sessionStorage.removeItem('clip-relay-admin-token');showLogin();return false;}
      return true;
    }catch(e){toast('连接失败');return false;}
  }

  function showLogin(){
    loginOverlay.style.display='';
    mainPanel.style.display='none';
    loginError.classList.remove('show');
    loginPwd.value='';
    loginPwd.type='password';
    pwdToggle.textContent='👁';
    loginPwd.focus();
  }

  function showLoginError(msg){
    loginError.textContent=msg;
    loginError.classList.add('show');
  }

  // 密码可见切换
  pwdToggle.addEventListener('click',()=>{
    const show=loginPwd.type==='password';
    loginPwd.type=show?'text':'password';
    pwdToggle.textContent=show?'🙈':'👁';
  });

  // 登录
  async function doLogin(){
    const pwd=loginPwd.value;
    if(!pwd){showLoginError('请输入密码');return}
    try{
      const resp=await fetch('/api/admin/login',{
        method:'POST',
        headers:{'Content-Type':'application/json'},
        body:JSON.stringify({password:pwd})
      });
      const data=await resp.json();
      if(data.error){showLoginError(data.error);return}
      sessionToken=data.token;
      sessionStorage.setItem('clip-relay-admin-token',sessionToken);
      loginOverlay.style.display='none';
      mainPanel.style.display='';
      loginError.classList.remove('show');
      if(data.recovered && data.message) alert(data.message);
      loadRooms();
    }catch(e){showLoginError('网络错误，请检查连接')}
  }

  loginBtn.addEventListener('click',doLogin);
  loginPwd.addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});

  // 退出
  logoutBtn.addEventListener('click',()=>{
    sessionToken='';
    sessionStorage.removeItem('clip-relay-admin-token');
    showLogin();
  });

  // 修改密码
  changePwdBtn.addEventListener('click',async()=>{
    const old=oldPwd.value;
    const nw=newPwd.value;
    if(!old||!nw){toast('请填写原密码和新密码');return}
    if(nw.length<3){toast('新密码至少3个字符');return}
    try{
      const resp=await api('/api/admin/change-password',{
        method:'POST',
        body:{oldPassword:old,newPassword:nw}
      });
      const data=await resp.json();
      if(data.error){toast(data.error);return}
      toast('密码已修改');
      alert('密码已修改。如忘记新密码，可用 RESET_KEY 恢复登录。');
      oldPwd.value='';newPwd.value='';
    }catch(e){toast('修改失败')}
  });


  function formatTime(iso){
    const d=new Date(iso);const p=n=>String(n).padStart(2,'0');
    return \`\${d.getFullYear()}-\${p(d.getMonth()+1)}-\${p(d.getDate())} \${p(d.getHours())}:\${p(d.getMinutes())}\`;
  }

  function ttlLabel(minutes){
    if(minutes===0)return'<span class="badge badge-permanent">永久</span>';
    if(minutes<60)return\`<span class="badge badge-temp">\${minutes}分钟</span>\`;
    if(minutes<1440)return\`<span class="badge badge-temp">\${Math.floor(minutes/60)}小时</span>\`;
    return\`<span class="badge badge-temp">\${Math.floor(minutes/1440)}天</span>\`;
  }

  async function loadRooms(){
    try{
      const resp=await api('/api/admin/rooms');
      if(resp.status===401){showLogin();return}
      const rooms=await resp.json();
      if(rooms.length===0){
        roomList.innerHTML='<tr><td colspan="8" style="text-align:center;color:var(--text-muted);padding:32px">暂无房间，请创建</td></tr>';
        return;
      }
      roomList.innerHTML=rooms.map(r=>{
        const link=\`\${location.protocol}//\${location.host}/?token=\${r.token}\`;
        const disabled=r.disabled?1:0;
        const toggleLabel=disabled?'启用':'停用';
        const toggleClass=disabled?'btn-success btn-sm':'btn-secondary btn-sm';
        const rowClass=disabled?' row-disabled':'';
        return\`<tr class="\${rowClass}">
          <td><strong>\${escapeHtml(r.name)}</strong></td>
          <td><span class="token">\${escapeHtml(r.token)}</span></td>
          <td>\${ttlLabel(r.ttl_minutes)}</td>
          <td>\${r.message_count}</td>
          <td>\${r.online_count||0}</td>
          <td style="font-size:12px;color:var(--text-muted)">\${formatTime(r.created_at)}</td>
          <td style="font-size:12px;color:var(--text-muted)">\${r.expires_at?formatTime(r.expires_at):'<span style="color:var(--text-muted)">—</span>'}</td>
          <td><div class="actions">
            <button class="btn btn-secondary btn-sm" data-copy="\${escapeAttr(link)}">复制链接</button>
            <button class="btn btn-sm btn-toggle" data-toggle="\${escapeAttr(r.token)}">\${toggleLabel}</button>
            <button class="btn btn-secondary btn-sm" data-clear="\${escapeAttr(r.token)}">清空</button>
            <button class="btn btn-danger btn-sm" data-delete="\${escapeAttr(r.token)}">删除</button>
          </div></td>
        </tr>\`;
      }).join('');

      roomList.querySelectorAll('[data-copy]').forEach(btn=>{
        btn.addEventListener('click',(e)=>{
          e.stopPropagation();
          showCopyPopover(btn, btn.dataset.copy);
        });
      });
      roomList.querySelectorAll('[data-toggle]').forEach(btn=>{
        btn.addEventListener('click',async()=>{
          const resp=await api('/api/admin/rooms/toggle',{
            method:'POST',
            body:{token:btn.dataset.toggle}
          });
          const data=await resp.json();
          if(data.error){toast(data.error);return}
          toast(data.disabled?'房间已停用':'房间已启用');
          loadRooms();
        });
      });
      roomList.querySelectorAll('[data-clear]').forEach(btn=>{
        btn.addEventListener('click',async()=>{
          if(!confirm('确定清空该房间所有消息？'))return;
          await api(\`/api/admin/rooms/\${btn.dataset.clear}/messages\`,{method:'DELETE'});
          toast('消息已清空');
          loadRooms();
        });
      });
      roomList.querySelectorAll('[data-delete]').forEach(btn=>{
        btn.addEventListener('click',async()=>{
          if(!confirm('确定删除该房间？房间和所有消息将被永久删除。'))return;
          await api(\`/api/admin/rooms/\${btn.dataset.delete}\`,{method:'DELETE'});
          toast('房间已删除');
          loadRooms();
        });
      });
    }catch(e){
      roomList.innerHTML='<tr><td colspan="8" style="text-align:center;color:var(--danger);padding:32px">加载失败</td></tr>';
    }
  }

  async function createNewRoom(){
    const name=roomName.value.trim();
    if(!name){toast('请输入房间名称');return}
    let ttl=parseInt(roomTTL.value);
    if(ttl===-1) ttl=parseInt(customTTL.value)||10;
    const token=roomToken.value.trim()||'';
    try{
      const resp=await api('/api/admin/rooms',{
        method:'POST',
        body:{name,token,ttl_minutes:ttl}
      });
      if(resp.status===401){showLogin();return}
      const data=await resp.json();
      if(data.error){toast(data.error);return}
      toast('房间创建成功！');
      roomName.value='';roomToken.value='';
      loadRooms();
    }catch(e){toast('创建失败')}
  }

  createBtn.addEventListener('click',createNewRoom);
  roomName.addEventListener('keydown',e=>{if(e.key==='Enter')createNewRoom()});
  roomTTL.addEventListener('change',()=>{
    customTTLField.style.display=parseInt(roomTTL.value)===-1?'block':'none';
  });

  function escapeHtml(s){
    const d=document.createElement('div');d.textContent=s;return d.innerHTML;
  }
  function escapeAttr(s){
    return s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  // 复制链接弹窗
  function showCopyPopover(anchor, fullLink) {
    const existing = document.querySelector('.copy-popover');
    if (existing) existing.remove();

    const popover = document.createElement('div');
    popover.className = 'copy-popover';

    const token = fullLink.split('token=')[1] || '';

    const localLink = \`http://localhost:\${location.port}/?token=\${token}\`;
    const lanLink = serverConfig.lanIP
      ? \`http://\${serverConfig.lanIP}:\${location.port}/?token=\${token}\`
      : null;
    const domainLink = serverConfig.domain
      ? \`https://\${serverConfig.domain}/?token=\${token}\`
      : null;

    let html = '';
    html += \`<button data-link="\${escapeAttr(localLink)}">🖥 本机访问<small>\${escapeHtml(localLink)}</small></button>\`;
    if (lanLink) {
      html += \`<button data-link="\${escapeAttr(lanLink)}">🏠 局域网访问<small>\${escapeHtml(lanLink)}</small></button>\`;
    }
    if (domainLink) {
      html += \`<div class="divider"></div>\`;
      html += \`<button data-link="\${escapeAttr(domainLink)}">🌐 公网访问<small>\${escapeHtml(domainLink)}</small></button>\`;
    }
    popover.innerHTML = html;
    document.body.appendChild(popover);

    // 智能定位：空间不够时显示在上方
    const rect = anchor.getBoundingClientRect();
    const popH = popover.offsetHeight;
    const spaceBelow = window.innerHeight - rect.bottom;
    const spaceAbove = rect.top;

    let top;
    if (spaceBelow >= popH + 8 || spaceBelow >= spaceAbove) {
      // 下方空间够，或下方空间多于上方
      top = rect.bottom + 4;
    } else {
      // 上方空间更多
      top = rect.top - popH - 4;
    }
    // 确保不超出屏幕
    top = Math.max(8, Math.min(top, window.innerHeight - popH - 8));

    popover.style.top = top + 'px';
    popover.style.left = Math.min(rect.left, window.innerWidth - 240) + 'px';
    popover.style.position = 'fixed';

    popover.querySelectorAll('button').forEach(b => {
      b.addEventListener('click', (e) => {
        e.stopPropagation();
        let ok = false;
        // 优先用 execCommand（同步，不丢用户手势）
        try {
          const ta = document.createElement('textarea');
          ta.value = b.dataset.link;
          ta.style.position = 'fixed'; ta.style.left = '-9999px'; ta.style.top = '-9999px';
          document.body.appendChild(ta);
          ta.select();
          document.execCommand('copy');
          ta.remove();
          ok = true;
        } catch (_) {}
        // execCommand 失败时尝试 Clipboard API
        if (!ok) {
          navigator.clipboard.writeText(b.dataset.link).then(() => ok = true).catch(() => {}).finally(() => {
            toast(ok ? '链接已复制！' : '复制失败，请手动复制');
            popover.remove();
          });
          return;
        }
        toast('链接已复制！');
        popover.remove();
      });
    });

    const close = (ev) => {
      if (!popover.contains(ev.target) && ev.target !== anchor) {
        popover.remove();
        document.removeEventListener('click', close);
      }
    };
    setTimeout(() => document.addEventListener('click', close), 10);
  }

  async function loadConfig() {
    try {
      const resp = await fetch('/api/config');
      serverConfig = await resp.json();
      domainInput.value = serverConfig.domain || '';
      if (serverConfig.domain) {
        domainStatus.textContent = '已配置: ' + serverConfig.domain;
        domainStatus.className = 'domain-status set';
      } else {
        domainStatus.textContent = '未配置';
        domainStatus.className = 'domain-status unset';
      }
    } catch (_) {}
  }

  // 保存域名
  saveDomainBtn.addEventListener('click', async () => {
    const domain = domainInput.value.trim();
    try {
      const resp = await api('/api/admin/domain', {
        method: 'POST',
        body: { domain }
      });
      if (resp.status === 401) { showLogin(); return; }
      const data = await resp.json();
      if (data.error) { toast(data.error); return; }
      serverConfig.domain = data.domain;
      domainStatus.textContent = '已配置: ' + data.domain;
      domainStatus.className = 'domain-status set';
      toast('域名已保存');
    } catch (e) { toast('保存失败'); }
  });

  // 初始化：检查登录状态
  (async()=>{
    await loadConfig();
    const authed=await checkAuth();
    if(authed){
      loginOverlay.style.display='none';
      mainPanel.style.display='';
      loadRooms();
    }
  })();
})();
</script>
</body>
</html>
`;
